import { Link } from 'react-router-dom';
import { Clock3, BookOpen, CircleGauge } from 'lucide-react';

const courses = [
  ['Security Guard Training', '40 Hours', 'Beginner', 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?q=80&w=800&auto=format&fit=crop'],
  ['First Aid & CPR (Level C)', '16 Hours', 'Certification', 'https://images.unsplash.com/photo-1571772996211-2f02c9727629?q=80&w=800&auto=format&fit=crop'],
  ['Loss Prevention', '20 Hours', 'Intermediate', 'https://images.unsplash.com/photo-1505238680356-667803448bb6?q=80&w=800&auto=format&fit=crop'],
];
export function CourseAndPortal(){return <section className="grid gap-6 lg:grid-cols-2"><div><div className="mb-4 flex items-center justify-between"><h2 className="text-3xl font-extrabold">FEATURED COURSES</h2><Link to="/courses" className="text-sm font-semibold text-academyBlue">View All Courses →</Link></div><div className="grid gap-4 md:grid-cols-3 lg:grid-cols-1 xl:grid-cols-3">{courses.map(([title,hours,level,img])=><article key={title} className="overflow-hidden rounded-xl border bg-white"><img src={img} className="h-36 w-full object-cover"/><div className="p-4"><h3 className="font-bold">{title}</h3><p className="mt-2 flex gap-4 text-sm text-slate-600"><span className="inline-flex items-center gap-1"><Clock3 className="h-3 w-3"/>{hours}</span><span className="inline-flex items-center gap-1"><BookOpen className="h-3 w-3"/>{level}</span></p><Link to="/courses/security-guard-training" className="mt-4 block w-full rounded-lg bg-academyBlue py-2 text-center text-sm font-semibold text-white">Learn More</Link></div></article>)}</div></div><div><h2 className="mb-4 text-3xl font-extrabold">STUDENT PORTAL PREVIEW</h2><div className="overflow-hidden rounded-xl border bg-white"><div className="grid grid-cols-[160px_1fr]"><aside className="bg-[#031547] p-3 text-sm text-white"><ul className="space-y-2">{['Dashboard','My Courses','Progress','Certificates','Messages','Account Settings','Logout'].map(i=><li key={i} className="rounded px-2 py-1 hover:bg-blue-600/40">{i}</li>)}</ul></aside><div className="p-4"><div className="grid gap-2 md:grid-cols-4">{[['Enrolled Courses','3'],['In Progress','2'],['Certificates Earned','1'],['Total Progress','68%']].map(([k,v])=><div className="rounded border p-2" key={k}><p className="text-xs text-slate-500">{k}</p><p className="text-xl font-bold">{v}</p></div>)}</div><div className="mt-4 grid gap-2 md:grid-cols-2"><div className="rounded border p-3"><h4 className="font-semibold">Recent Activity</h4><ul className="mt-2 space-y-2 text-sm text-slate-600"><li>Completed: Security Awareness</li><li>In Progress: Security Guard Training</li><li>Upcoming: First Aid & CPR</li></ul></div><div className="rounded border p-3"><h4 className="font-semibold">Progress Overview</h4><div className="mt-5 flex items-center justify-center"><div className="flex h-24 w-24 items-center justify-center rounded-full border-[10px] border-blue-500 text-xl font-bold text-slate-700">68%</div></div><p className="mt-3 inline-flex items-center gap-2 text-sm"><CircleGauge className="h-4 w-4 text-blue-500"/> On track</p></div></div></div></div></div></div></section>}
